name: Rebuild Lime Linux NDLL
on:
  workflow_dispatch

jobs:
  rebuild_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.2

      - name: Setup Lime
        uses: actions/checkout@v4.1.5
        with:
          repository: FunkinCrew/lime
          submodules: true
          path: 'lime'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev

      - name: Rebuild Lime
        run: |
          haxelib dev lime lime
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib install hxcpp --quiet
          haxelib run lime rebuild linux -release -64 -clean
          haxelib run lime rebuild linux -release -clean
        # TODO: See if debug files need rebuilding as well

      - name: Upload 32-bit NDLLs
        uses: actions/upload-artifact@v4
        with:
          name: linuxNDLL
          path: lime/ndll/Linux
          compression-level: 0
          if-no-files-found: error

      - name: Upload 64-bit NDLLs
        uses: actions/upload-artifact@v4
        with:
          name: linuxNDLL64
          path: lime/ndll/Linux64
          compression-level: 0
          if-no-files-found: error

